### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ardera** [yoav-lavi/melody#10]
Hey,
really like this project!

What do you think about writing some examples? Maybe a well-written example (with comments) that'll match email adresses, to really show the benefit of using this.

**Comment by yoav-lavi** [comment]
Thank you!

The README has a few examples and I'm working on adding more, I think the most useful examples will be added once a few more features are supported (e.g. email matching).

Leaving open for now

**Comment by yoav-lavi** [comment]
Closing since I've added a few more and more still will be added
