### ISSUE TITLE
Feature: Web App for compiling and trying melody

### ISSUE THREAD

**Issue by ShivamJoker** [yoav-lavi/melody#24]
It would be great to have a web app where users can try it out without installing it on their local system.

I think we can compile this to WASM to do that, or if you any plans let me know.

Also if you can create the wasm file I may be able to put a simple web app

**Comment by Marcus0086** [comment]
I was going to ask the same. I have compiled this to wasm and currently experimenting with the UI. Lemme know if you want to see it.

**Comment by ShivamJoker** [comment]
Sure thing share the repo with us

**Comment by yoav-lavi** [comment]
Looking into this, stay tuned!

**Comment by Marcus0086** [comment]
Yea sure 😄 
Here: https://github.com/Marcus0086/melody-wasm

**Comment by yoav-lavi** [comment]
@Marcus0086 @ShivamJoker I've recently added WASM bindings within the project, see `crates/melody_wasm`. Looking into an interactive editor

**Comment by Marcus0086** [comment]
Cool @yoav-lavi

**Comment by Marcus0086** [comment]
@yoav-lavi @ShivamJoker I'm thinking of making a live editor `mermaid.live`. What do you guys think?

**Comment by ShivamJoker** [comment]
What's mermaid here?

**Comment by yoav-lavi** [comment]
I've deployed a very rough draft of a playground here: https://melody-playground-yoav-lavi.vercel.app, welcome to try it
