### ISSUE TITLE
Allow printing regex without wrapping `/` and trailing newline

### ISSUE THREAD

**Issue by haxscramper** [yoav-lavi/melody#57]
**Describe the solution you'd like**

Allow generating regular expressions without leading and trailing `/` as well as trailing newline. 

**Additional context**

This would make it easier to use in various configuration file templating solutions, such as m4. I'm generating a configuration file for ArchibeBox, and I need to setup a `URL_BLACKLIST` variable, which is a regex literal. Naturally, I would prefer to write 

```c
"http";
option of "s";
"://";
`(.+)?`;
either {
    "amazon.com";
    "youtube.com";
}
`.*`;
```

over `r'https?://(.+)?(?:amazon\.com|youtube\.com).*'`, but in order to interpolate melody regex results, I had to use it in conjunction with `sed` and `tr`.

```m4
URL_BLACKLIST = r'syscmd(melody link.melody | sed 's!^/!! ; s!/$!!' | tr -d '\n')'
```

Which is not *terribly* difficult to add and maintain, still worse than 

```m4
URL_BLACKLIST = r'syscmd(melody --standalone-regex link.melody)'
```

**Comment by yoav-lavi** [comment]
Sounds completely reasonable, will add this. 

Note that melody files are `.mdy` if you use the VSCode extension, might be a good idea to add `.melody` as an option as well.

Also note that `(.+)?` is equivalent to `option of capture { some of <char>; }` and `.*` is equivalent to `any of <char>;`, if you're using raw patterns there to make up for missing functionality you can use those, but if you're using it to interleave regex where convenient then that's the intended use 😄

**Comment by haxscramper** [comment]
This is my first time using melody, so thanks for corrections on the `.*` one, I somehow didn't realize you can do `any of <thing>`. On the `(.+)?` - that is a typo on my side, and I actually wanted a non-greedy one-or-more, so it should be a `.+?` and from what I can see there is no "non-greedy" modifier for `some`.

**Comment by yoav-lavi** [comment]
Melody is 19 days old , so there aren't many experts yet haha. Regarding lazy - it's something I want to add at some point but still thinking of what the syntax would be

**Comment by yoav-lavi** [comment]
Starting from `v0.12.0` clean output (no // and newline) will be used

**Comment by yoav-lavi** [comment]
@haxscramper I've reverted the newline change, it looks like other CLIs do add a newline even when piping and it causes some visual issues otherwise. Let me know if it's a problem, I may be able to add a flag to enable that behavior

**Comment by haxscramper** [comment]
Wrapping `//` were more problematic, and if lack of trailing newline causes inconsistencies with other CLI tools, it is better to keep newline.

**Comment by yoav-lavi** [comment]
@haxscramper what's that language you're using in the example? 

```
URL_BLACKLIST = r'syscmd(melody --standalone-regex link.melody)'
```

trying to see if e.g. `echo` acts the same

**Comment by haxscramper** [comment]
I was using `m4` for templating, and `echo 12` works differently. 

```m4
URL_BLACKLIST = r'syscmd(echo 12)'
```

Expands into 

```m4
URL_BLACKLIST = r'12
'
```

**Comment by yoav-lavi** [comment]
@haxscramper isn't that the same? As in, with a newline?

**Comment by yoav-lavi** [comment]
```
URL_BLACKLIST = r'syscmd(echo 12)'
URL_BLACKLIST = r'12
'
```

```
URL_BLACKLIST = r'syscmd(echo "3 of 'a';" | melody)'
URL_BLACKLIST = r'a{3}
'
```

**Comment by haxscramper** [comment]
Not sure what do you mean, but if I call `echo -n 12` (no newline), it expands into `r'12'`. Trimming trailing newline is not that big of a deal, and probably it has more to do with `m4` being stupider than it needs to be. Python works

**Comment by yoav-lavi** [comment]
Yeah looks like it's an m4 issue: 

```py
>>> x = os.system("echo '<end>;' | melody")
$
```
