### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by PerfectlyFineCode** [yoav-lavi/melody#62]
**Describe the solution you'd like**
Any planned support for Windows in the future?
Windows Subsystem for Linux exists, yes. But is there a planned support for native Windows?

**Comment by yoav-lavi** [comment]
Hey @PerfectlyFineCode!
Have you tried downloading Melody from cargo on a Windows machine and it didn't work? Melody doesn't use anything platform specific so between cargo and compiling from source it should work. If not let me know, I don't have a Windows machine available but we could open an issue
