### ISSUE TITLE
Invalid repetition range should give an error

### ISSUE THREAD

**Issue by alpheratz0** [yoav-lavi/melody#65]
**Describe the bug**
The following melody code should not compile, but it does and generates an invalid regex because the repetition range cannot be from 2 to 0.
```rs
2 to 0 of match { "test"; }
```

`crates/melody_compiler/src/ast/source_to_ast.rs`

```rs
Rule::quantifier_range => {
    let (start, end) = first_last_inner_str(kind)?;

    // maybe check here that end >= start?

    Node::Quantifier(Quantifier {
        kind: QuantifierKind::Range {
            start: start.to_owned(),
            end: end.to_owned(),
        },
        lazy,
        expression: Box::new(expression),
    })
}
```

**To Reproduce**
```sh
$ echo '2 to 0 of match { "test"; }' | melody /dev/stdin
> (?:test){2,0}
```

**Expected behavior**
An error.

**Comment by yoav-lavi** [comment]
Right you are, will look into fixing this soon. Thanks!

**Comment by yoav-lavi** [comment]
Fixed in https://github.com/yoav-lavi/melody/commit/c856f06640aa70f5b37498dcc57d992c39e840e6, will release a version with the fix soon
