### ISSUE TITLE
Quantifiers add unnecessary non-capturing group

### ISSUE THREAD

**Issue by trezy** [yoav-lavi/melody#70]
**Describe the bug**
When using `some of ...` with symbols, a non-capturing group is added unconditionally. This is unnecessary for most individual symbols (e.g. `<word>`).

**To Reproduce**

1. Open the [Melody Playground]()
2. Write a program which only uses `some of ...` with a single symbol, e.g.:
    ```melody
    some of <word>;
    ```
3. Review the output

**Expected behavior**
RegEx output should only add wrap things with non-capturing groups if necessary or if implicitly required (via `match {}`).

**Examples**
```melody
any of <word>;
// Outputs /(?:\w)*/

any of "a";
// Outputs /a*/

some of <word>;
// Outputs /(?:\w)+/

some of "a";
// Outputs /a+/

option of <word>;
// Outputs /(?:\w)?/

option of "a";
// Outputs /a?/
```

**Comment by yoav-lavi** [comment]
This is an issue of the current implementation which checks for more than a single character (https://github.com/yoav-lavi/melody/blob/main/crates/melody_compiler/src/regex/utils.rs#3) which is always correct but not ideal, it should be changed to something that can identify sequences that can directly be quantified without grouping.

Thanks for the report!

**Comment by yoav-lavi** [comment]
@trezy I think this should solve it, are you aware of any other cases that are directly quantifiable?

# Original
```rs
pub fn wrap_quantified(value: String) -> String {
    let is_grouped = value.starts_with('(') && value.ends_with(')');
    if !is_grouped && value.chars().count() > 1 {
        format!("(?:{value})")
    } else {
        value
    }
}
```

# Updated

```rs
pub fn wrap_quantified(value: String) -> String {
    if !directly_quantifiable(&value) {
        format!("(?:{value})")
    } else {
        value
    }
}

macro_rules! one_of {
    ($($expr: expr;)+) => {
        $(if $expr {
            return true;
        };)*
        return false;
    };
}

fn directly_quantifiable(value: &str) -> bool {
    if value.chars().count() > 1 {
        one_of! {
            value.starts_with('\\');
            value.starts_with('(') && value.ends_with(')');
            value.starts_with('[') && value.ends_with(']');
        }
    }
    return true;
}
```

**Comment by yoav-lavi** [comment]
Fixed
