### ISSUE TITLE
Please make this a Crate for third party libraries

### ISSUE THREAD

**Issue by MierenManz** [yoav-lavi/melody#8]
This project seems really interesting and really nice to use in things that are web related like a nodejs server.
I would love to make some small bindings to this for node and deno through their ffi systems but sadly enough this is not a crate.

Would there be any way that this could also be a crate?

**Comment by yoav-lavi** [comment]
@MierenManz the plan is to make Melody available as both a build step (for TS/JS projects, like e.g. SASS) and expose a crate once the language is more stable, stay tuned!
Thank you for the kind words!

**Comment by MierenManz** [comment]
Thanks for the fast reply. I will look forward seeing this project grow. Would love to make this into bindings with either wasm or ffi for JavaScript runtimes :D

**Comment by yoav-lavi** [comment]
Just split the CLI and compiler into two crates, so I'll be able to expose the compiler soon

**Comment by MierenManz** [comment]
Thank you so much. I'm excited to use this for future projects :D

**Comment by yoav-lavi** [comment]
Hey @MierenManz, this should work: https://crates.io/crates/melody_compiler

I may change the name of the crate later on but for now it should allow you to use it

**Comment by yoav-lavi** [comment]
@MierenManz note that there are no docs yet but you can look at `melody_cli` for a usage example in the meantime

**Comment by MierenManz** [comment]
@yoav-lavi that is alright. If I can get it to work expect a thread in the discussions tab :P

**Comment by yoav-lavi** [comment]
@MierenManz there's also a WASM binding but that's not on NPM yet
