### ISSUE TITLE
Link https://yoav-lavi.github.io/melody/ returns 404

### ISSUE THREAD

**Issue by Gys** [yoav-lavi/melody#83]
**Describe the bug**
The playground https://melody-playground.vercel.app/ has a 'docs' link https://yoav-lavi.github.io/melody/ which returns a 404 if clicked.

**Comment by yoav-lavi** [comment]
Thanks @Gys! Will fix soon. The docs are at https://yoav-lavi.github.io/melody/book/ if you need them

**Comment by yoav-lavi** [comment]
Fixed
