### ISSUE TITLE
`not <char>` emits `[^.]`

### ISSUE THREAD

**Issue by Aloso** [yoav-lavi/melody#84]
**Describe the bug**
`not <char>` produces the incorrect output, since the dot does not match an arbitrary character within character set.

**To Reproduce**
Open [this playground](https://melody-playground.vercel.app?content=bm90JTIwJTNDY2hhciUzRSUzQg==).

**Expected behavior**
An error message.

**Comment by yoav-lavi** [comment]
Hey @Aloso, thanks! 

Will hopefully be able to look into this soon. I don't imagine this has any actual use (wouldn't "not char" basically be an empty string?) but it makes sense to return an error.

How's it going with Pomsky?

**Comment by Aloso** [comment]
> wouldn't "not char" essentially be an empty string?

Not quite. A character set always matches exactly one code point (exception: JavaScript regexes can also match a surrogate, which is _one half_ of a UTF-16 code point that uses 4 bytes).

That means that `[]` does not match any code point, but it also does not match the empty string, because it expects one code point, but matching the code point never succeeds. So it actually matches nothing.

Other regex engines besides JavaScript do not allow `[]`. In ERE and PCRE, `[]]` matches a `]` character, which does not need to be escaped with a backslash. A `]` directly following the `[` is just treated like `\]`. So if you want to match nothing in PCRE, you can't use `[]`, you have to use `[^\s\S]`.

But I think it doesn't make sense to support that in Melody (or Pomsky), because when do you ever need that?

**Comment by Aloso** [comment]
> How's it going with Pomsky?

I wrote you an email about that, which I guess you didn't receive. It's not super important, but I'll open an issue for it 🙂

**Comment by yoav-lavi** [comment]
Thanks for the detailed explanation!

When referring to an empty string I didn't specifically mean if using a character class:

It's true that Melody uses character classes for some instances of `not`, but that's more of an implementation detail. For instance `not <digit>` would be `\D` - So `not <char>` wouldn't necessarily have to be a set in this case.

It could theoretically translate to something like `((?=))`

That being said it doesn't seem like something that'd make sense to allow

**Comment by yoav-lavi** [comment]
Fixed, will be released soon. Thanks!
