### ISSUE TITLE
Incorrectly escaping `-` character

### ISSUE THREAD

**Issue by unvariant** [yoav-lavi/melody#90]
**Describe the bug**
According to the regress crate, Melody incorrectly escapes the `-` character.
I am not very familiar with regex, so I am not sure if this is a bug with melody or regress.

**To Reproduce**
src/main.rs
```
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let regex = r#"
    "-";
    "#;
    _ = regress::Regex::new(&melody_compiler::compiler(regex)?)?;
    Ok(())
}
```

Cargo.toml
```
[package]
name = "re"
version = "0.1.0"
edition = "2021"

[dependencies]
melody_compiler = "0.18.1"
regress = "0.4.1"
```

```
cargo run
   Compiling re v0.1.0 (re)
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `target/debug/re`
Error: Error { text: "Invalid character escape" }
```

**Expected behavior**
Expected the code to compile the regex without any errors.

**Desktop**
 - OS: macOS
 - Version: 12.4

**Comment by yoav-lavi** [comment]
@unvariant thanks for the report!
This is a bug, `-` is a special character in some contexts in regex (e.g. `[A-Z]`) but it shouldn't be escaped in your example. Will look into this

**Comment by yoav-lavi** [comment]
Will be fixed in the next version
